@startuml
class ComentarioRepositorio {
    - _contexto : AppDBContext
    + ComentarioRepositorio(AppDBContext:AppDBContext)
    + <<async>> GuardarContext() : Task
    + <<async>> Listar() : Task<IEnumerable<Comentario>>
    + <<async>> BuscarXId(id:int) : Task<Comentario>
    + <<async>> BuscarPostXId(postId:int) : Task<IEnumerable<Comentario>>
    + <<async>> Crear(comentario:Comentario) : Task
    + <<async>> Editar(comentario:Comentario) : Task
    + <<async>> Eliminar(id:int) : Task
}
IComentarioRepositorio <|-- ComentarioRepositorio
@enduml
