@startuml
class PostItemRepositorio {
    - _context : AppDBContext
    + PostItemRepositorio(AppDBContext:AppDBContext)
    + <<async>> Listar() : Task<IEnumerable<PostItem>>
    + <<async>> Crear(postItem:PostItem) : Task
    + <<async>> Editar(postItem:PostItem) : Task
    + <<async>> Eliminar(id:int) : Task
    + BuscarXId(id:int) : PostItem
    + <<async>> postExiste(id:int) : Task<bool>
}
IPostItemRepositorio <|-- PostItemRepositorio
@enduml
