@startuml
class UsuarioRepositorio {
    - AppDBContext : AppDBContext
    + UsuarioRepositorio(AppDBContext:AppDBContext)
    + <<async>> Listar() : Task<IEnumerable<Usuario>>
    + Crear(postItem:Usuario) : void
    + Eliminar(id:int) : void
    + <<async>> BuscarXId(id:int) : Task<Usuario>
    + Modificar(postItem:Usuario) : void
}
IUsuarioRepositorio <|-- UsuarioRepositorio
@enduml
