@startuml
class PostItemController {
    - postItemService : IPostItemServicio
    + PostItemController(postItemService:IPostItemServicio)
    + <<async>> PostItemAsync(postItem:PostItemDTO) : Task<IActionResult>
    + <<async>> Comment(comentario:ComentarioDTO, id:int) : Task<IActionResult>
    + <<async>> DeletePostItem(id:int) : Task<IActionResult>
    + <<async>> UpdatePostItem(id:int, postItem:PostItem) : Task<IActionResult>
    + <<async>> GetComments(id:int) : Task<IActionResult>
    + <<async>> GetAllPostsItems() : Task<IActionResult>
}
ControllerBase <|-- PostItemController
@enduml
