@startuml
class PostItemServicioTests {
    - <<readonly>> postItemSrvTest : IPostItemServicio
    - <<readonly>> usuarioRepoTest : Mock<IUsuarioRepositorio>
    - <<readonly>> postItemRepoTest : Mock<IPostItemRepositorio>
    - <<readonly>> comentarioRepoTest : Mock<IComentarioRepositorio>
    + PostItemServicioTests()
    + <<async>> Creando_PostItemAsync() : Task
    + <<async>> Intruso_Creando_PostItemAsync() : Task
}
@enduml
