@startuml
interface IPostItemServicio {
    ListarPostsItems() : Task<IEnumerable<PostItem>>
    GetPostItemById(id:int) : Task<PostItem>
    CrearPostItem(postItem:PostItem) : Task<IEnumerable<ErrorBase>>
    EditarPostItem(postItem:PostItem) : Task<IEnumerable<ErrorBase>>
    EliminarPostItem(id:int) : Task
    CrearComentario(comment:Comentario) : Task<IEnumerable<ErrorBase>>
    GetComentariosByPostItemId(postId:int) : Task<IEnumerable<Comentario>>
}
@enduml
