@startuml
interface IUsuarioServicio {
    GetUsuarios() : Task<IEnumerable<Usuario>>
    GetUsuario(id:int) : Task<Usuario>
    CrearUsuario(user:Usuario) : Task<IEnumerable<ErrorApp>>
    EditarUsuario(user:Usuario) : Task<IEnumerable<ErrorApp>>
    EliminarUsuario(id:int) : Task
}
@enduml
