@startuml
class UsuariosServicio {
    - _contexto : IUsuarioRepositorio
    + UsuariosServicio(usuarioRepositorio:IUsuarioRepositorio)
    + CrearUsuario(usuario:Usuario) : Task
    + <<async>> GetUsuarios() : Task<IEnumerable<Usuario>>
    + GetUsuario(id:int) : Task<Usuario>
}
IUsuarioServicio <|-- UsuariosServicio
@enduml
