@startuml
interface IPostItemRepositorio {
    GuardarContext() : Task
    Listar() : Task<IEnumerable<PostItem>>
    Crear(postItem:PostItem) : Task
    Eliminar(id:int) : Task
    Editar(postItem:PostItem) : Task
    BuscarXId(Id:int) : Task<PostItem>
    postExiste(id:int) : Task<bool>
}
@enduml
