@startuml
class ComentarioValidador {
    - postItemRepository : IPostItemRepositorio
    + ComentarioValidador(postItemRepository:IPostItemRepositorio)
    + Validar(comentario:Comentario) : IEnumerable<ErrorApp>
}
"IValidadorServicio`1" "<Comentario>" <|-- ComentarioValidador
@enduml
