@startuml
class PostValidador {
    - userRepository : IUsuarioRepositorio
    + PostValidador(userRepository:IUsuarioRepositorio)
    + Validar(postItem:PostItem) : IEnumerable<ErrorBase>
}
"IValidadorServicio`1" "<PostItem>" <|-- PostValidador
@enduml
