name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ CICD ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.401
        #dotnet-version: '3.1.x'
    - run: dotnet restore ./BackEnd/App.Api/
    - run: dotnet build --configuration Release --no-restore ./BackEnd/App.Api/App.Api.csproj
    - run: dotnet test ${{github.workspace}}/BackEnd/App.Test/App.Test.csproj --no-restore --verbosity normal --configuration Release
